import { Opportunity } from '@/types/opportunity';

export const MOCK_OPPORTUNITIES: Opportunity[] = [
    {
        id: '1',
        topic: 'Big Lot Electronics Export',
        customerName: 'John Doe',
        companyName: 'Tech Corp USA',
        amount: 500000,
        currency: 'THB',
        stage: 'inquiry',
        probability: 20,
        closeDate: '2024-12-01',
        ownerName: 'Sales Rep A',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '2',
        topic: 'Monthly Fruit Shipment',
        customerName: 'Jane Smith',
        companyName: 'Fresh Foods Ltd',
        amount: 120000,
        currency: 'THB',
        stage: 'quoting',
        probability: 50,
        closeDate: '2024-11-20',
        ownerName: 'Sales Rep B',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '3',
        topic: 'Urgent Medical Supplies',
        customerName: 'Dr. Strange',
        companyName: 'Global Health Inc',
        amount: 850000,
        currency: 'THB',
        stage: 'pending_docs',
        probability: 80,
        closeDate: '2024-11-15',
        ownerName: 'Sales Rep A',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '4',
        topic: 'Textile Samples',
        customerName: 'Alice Brown',
        companyName: 'Fashion Week Co',
        amount: 15000,
        currency: 'THB',
        stage: 'inquiry',
        probability: 10,
        closeDate: '2025-01-10',
        ownerName: 'Sales Rep C',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    },
    {
        id: '5',
        topic: 'Heavy Machinery Parts',
        customerName: 'Bob Builder',
        companyName: 'Build It Right',
        amount: 2500000,
        currency: 'THB',
        stage: 'closed_won',
        probability: 100,
        closeDate: '2024-10-30',
        ownerName: 'Sales Rep A',
        createdAt: new Date().toISOString(),
        updatedAt: new Date().toISOString(),
    }
];
